---

- name: Download the docker image
  command: docker pull openbmp/aio

- name: Create MySQL volumes
  command: mkdir -p /var/openbmp/mysql

- name: Set Permissions
  command: chmod 777 /var/openbmp/mysql
